services:
  - type: web
    name: fashnova-ai
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: WEATHER_API_KEY
        sync: false   # set in Render dashboard
